import { AdminUser, UploadedCourse, UploadedVideo, ModerationReport, AuditLogEntry } from '../types/admin';

export const INITIAL_USERS: AdminUser[] = [
  {
    id: 'usr_1',
    name: 'Rohan Verma',
    email: 'rohan.design@skillbuilder.io',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300',
    role: 'MENTOR',
    status: 'ACTIVE',
    trustScore: 98,
    uploadsCount: 6,
    swapCount: 34,
    warningCount: 0,
    phone: '+91 98765 43210',
    location: 'Bengaluru, India',
    joinedDate: 'Jan 15, 2026',
    lastActive: '10 mins ago',
  },
  {
    id: 'usr_2',
    name: 'Aditi Sinha',
    email: 'aditi.pastry@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300',
    role: 'MENTOR',
    status: 'ACTIVE',
    trustScore: 96,
    uploadsCount: 8,
    swapCount: 42,
    warningCount: 0,
    phone: '+91 98231 11223',
    location: 'Mumbai, India',
    joinedDate: 'Feb 02, 2026',
    lastActive: '1 hour ago',
  },
  {
    id: 'usr_3',
    name: 'Priya Sharma',
    email: 'priya.dev@skillbuilder.io',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300',
    role: 'MENTOR',
    status: 'ACTIVE',
    trustScore: 99,
    uploadsCount: 12,
    swapCount: 56,
    warningCount: 0,
    phone: '+91 91234 56789',
    location: 'Hyderabad, India',
    joinedDate: 'Jan 05, 2026',
    lastActive: '2 mins ago',
  },
  {
    id: 'usr_4',
    name: 'Rohit Kumar (Bad Practice Demo)',
    email: 'rohit.scam99@tempmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    role: 'MENTOR',
    status: 'WARNED',
    trustScore: 42,
    uploadsCount: 2,
    swapCount: 1,
    warningCount: 2,
    phone: '+91 99887 76655',
    location: 'Delhi, India',
    joinedDate: 'Mar 10, 2026',
    lastActive: 'Yesterday',
    reasonBlocked: 'Flagged for uploading copyrighted video course from YouTube and misleading learners.'
  },
  {
    id: 'usr_5',
    name: 'Vikram Rajput',
    email: 'vikram.hacker@proton.me',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300',
    role: 'LEARNER',
    status: 'BLOCKED',
    trustScore: 12,
    uploadsCount: 0,
    swapCount: 0,
    warningCount: 3,
    phone: '+91 90000 12345',
    location: 'Pune, India',
    joinedDate: 'Mar 01, 2026',
    lastActive: '3 days ago',
    reasonBlocked: 'Attempted account spoofing, harassment in peer encrypted chat, and multiple community reports.',
    blockedAt: 'Mar 16, 2026'
  },
  {
    id: 'usr_6',
    name: 'Ananya Deshmukh',
    email: 'ananya.learner@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300',
    role: 'LEARNER',
    status: 'ACTIVE',
    trustScore: 92,
    uploadsCount: 0,
    swapCount: 15,
    warningCount: 0,
    phone: '+91 97654 32190',
    location: 'Jaipur, India',
    joinedDate: 'Feb 18, 2026',
    lastActive: 'Just now',
  },
  {
    id: 'usr_7',
    name: 'Raman Rathore',
    email: 'raman.guitar@skillbuilder.io',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300',
    role: 'MENTOR',
    status: 'ACTIVE',
    trustScore: 97,
    uploadsCount: 9,
    swapCount: 29,
    warningCount: 0,
    phone: '+91 96543 21876',
    location: 'Chandigarh, India',
    joinedDate: 'Jan 22, 2026',
    lastActive: '45 mins ago',
  },
  {
    id: 'usr_8',
    name: 'Carlos Mendez',
    email: 'carlos.spanish@skillbuilder.io',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300',
    role: 'MENTOR',
    status: 'ACTIVE',
    trustScore: 94,
    uploadsCount: 5,
    swapCount: 18,
    warningCount: 0,
    phone: '+34 612 345 678',
    location: 'Madrid, Spain',
    joinedDate: 'Feb 10, 2026',
    lastActive: '3 hours ago',
  }
];

export const INITIAL_COURSES: UploadedCourse[] = [
  {
    id: 'crs_1',
    title: 'Mastering Artisan French Cake Making',
    mentorId: 'usr_2',
    mentorName: 'Aditi Sinha',
    mentorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300',
    category: 'Culinary Arts',
    price: '₹1,499',
    duration: '3h 45m',
    lessonsCount: 8,
    rating: 4.98,
    status: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800',
    createdAt: 'Feb 05, 2026'
  },
  {
    id: 'crs_2',
    title: 'Modern Design Systems in Figma & Tokens',
    mentorId: 'usr_1',
    mentorName: 'Rohan Verma',
    mentorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300',
    category: 'Design & Art',
    price: '₹2,199',
    duration: '4h 20m',
    lessonsCount: 12,
    rating: 4.92,
    status: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    createdAt: 'Jan 20, 2026'
  },
  {
    id: 'crs_3',
    title: 'Android Architecture & Jetpack Compose 2026',
    mentorId: 'usr_3',
    mentorName: 'Priya Sharma',
    mentorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300',
    category: 'Tech & Coding',
    price: '₹2,999',
    duration: '6h 15m',
    lessonsCount: 16,
    rating: 4.96,
    status: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
    createdAt: 'Jan 12, 2026'
  },
  {
    id: 'crs_4',
    title: 'Acoustic Fingerstyle & Harmonic Masterclass',
    mentorId: 'usr_7',
    mentorName: 'Raman Rathore',
    mentorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300',
    category: 'Music',
    price: '₹1,299',
    duration: '2h 50m',
    lessonsCount: 6,
    rating: 4.95,
    status: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
    createdAt: 'Jan 28, 2026'
  },
  {
    id: 'crs_5',
    title: 'Pirated Web Dev Ripped Lectures (Suspicious)',
    mentorId: 'usr_4',
    mentorName: 'Rohit Kumar (Bad Practice Demo)',
    mentorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    category: 'Tech & Coding',
    price: '₹499',
    duration: '1h 10m',
    lessonsCount: 3,
    rating: 2.10,
    status: 'FLAGGED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
    flagReason: 'Copyright strike submitted by external educator. Low quality re-upload.',
    createdAt: 'Mar 12, 2026'
  }
];

export const INITIAL_VIDEOS: UploadedVideo[] = [
  {
    id: 'vid_1',
    courseId: 'crs_4',
    courseTitle: 'Acoustic Fingerstyle & Harmonic Masterclass',
    mentorName: 'Raman Rathore',
    mentorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300',
    title: 'Lesson 1: Acoustic Guitar Anatomy & Your Very First Chord',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600',
    duration: '10:30',
    views: 18420,
    likes: 1240,
    category: 'Music',
    status: 'APPROVED',
    flaggedForBadPractice: false,
    uploadDate: 'Sep 10, 2026'
  },
  {
    id: 'vid_2',
    courseId: 'crs_3',
    courseTitle: 'Android Architecture & Jetpack Compose 2026',
    mentorName: 'Priya Sharma',
    mentorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300',
    title: 'Kotlin Coroutines, Flow, & StateFlow Production Patterns',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600',
    duration: '14:20',
    views: 24100,
    likes: 1980,
    category: 'Tech & Coding',
    status: 'APPROVED',
    flaggedForBadPractice: false,
    uploadDate: 'Sep 12, 2026'
  },
  {
    id: 'vid_3',
    courseId: 'crs_1',
    courseTitle: 'Mastering Artisan French Cake Making',
    mentorName: 'Aditi Sinha',
    mentorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300',
    title: 'Classic French Sponge Cake (Génoise) & Whipped Ganache',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600',
    duration: '18:45',
    views: 15300,
    likes: 980,
    category: 'Culinary Arts',
    status: 'APPROVED',
    flaggedForBadPractice: false,
    uploadDate: 'Sep 08, 2026'
  },
  {
    id: 'vid_4',
    courseId: 'crs_5',
    courseTitle: 'Pirated Web Dev Ripped Lectures (Suspicious)',
    mentorName: 'Rohit Kumar (Bad Practice Demo)',
    mentorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    title: 'Full Stack MERN Clone (Stolen Watermarked Video)',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600',
    duration: '08:15',
    views: 310,
    likes: 4,
    category: 'Tech & Coding',
    status: 'FLAGGED',
    flaggedForBadPractice: true,
    flagReason: 'Watermark of external YouTube channel visible. DMCA notice flagged by automated scan.',
    uploadDate: 'Sep 17, 2026'
  }
];

export const INITIAL_REPORTS: ModerationReport[] = [
  {
    id: 'rep_1',
    reportedUserId: 'usr_4',
    reportedUserName: 'Rohit Kumar (Bad Practice Demo)',
    reportedUserAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    reporterName: 'Ananya Deshmukh',
    type: 'COPYRIGHT_INFRINGEMENT',
    severity: 'HIGH',
    targetContent: 'Full Stack MERN Clone (Stolen Watermarked Video)',
    targetType: 'VIDEO',
    description: 'This mentor re-uploaded free tutorial videos from a popular YouTube instructor and put a price tag on them.',
    timestamp: '2 hours ago',
    status: 'PENDING'
  },
  {
    id: 'rep_2',
    reportedUserId: 'usr_5',
    reportedUserName: 'Vikram Rajput',
    reportedUserAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300',
    reporterName: 'Aditi Sinha',
    type: 'HARASSMENT_OR_ABUSE',
    severity: 'CRITICAL',
    targetContent: 'Encrypted Peer Chat #conv_892',
    targetType: 'CHAT_MESSAGE',
    description: 'User repeatedly sent offensive messages and threatened to leave fake negative reviews if swap request was declined.',
    timestamp: '1 day ago',
    status: 'PENDING'
  },
  {
    id: 'rep_3',
    reportedUserId: 'usr_4',
    reportedUserName: 'Rohit Kumar (Bad Practice Demo)',
    reportedUserAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    reporterName: 'Priya Sharma',
    type: 'SPAM_OR_MALWARE',
    severity: 'MEDIUM',
    targetContent: 'External Telegram Link in Video Description',
    targetType: 'VIDEO',
    description: 'Video description invites students to an external crypto/telegram channel for course downloads.',
    timestamp: '2 days ago',
    status: 'PENDING'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log_1',
    adminName: 'Chief Administrator',
    action: 'USER_BLOCKED',
    target: 'Vikram Rajput (usr_5)',
    details: 'Account permanently suspended. Reason: Persistent harassment and violation of peer safety policy.',
    timestamp: 'Mar 16, 2026, 14:22',
    severity: 'DANGER'
  },
  {
    id: 'log_2',
    adminName: 'Chief Administrator',
    action: 'USER_WARNED',
    target: 'Rohit Kumar (usr_4)',
    details: 'Official warning issued for uploading duplicate content without copyright attribution.',
    timestamp: 'Mar 14, 2026, 11:05',
    severity: 'WARNING'
  },
  {
    id: 'log_3',
    adminName: 'Chief Administrator',
    action: 'CONTENT_REMOVED',
    target: 'Phishing Skill Listing #sk_44',
    details: 'Skill listing removed from public search index due to policy violations.',
    timestamp: 'Mar 13, 2026, 09:30',
    severity: 'DANGER'
  },
  {
    id: 'log_4',
    adminName: 'Chief Administrator',
    action: 'REPORT_RESOLVED',
    target: 'Report #rep_902',
    details: 'Marked resolved after mentor verification review.',
    timestamp: 'Mar 11, 2026, 16:45',
    severity: 'SUCCESS'
  }
];
